const functions = require("firebase-functions");
const admin = require("firebase-admin");
const config = functions.config().firebase;
try {
  admin.initializeApp(config);
} catch (e) {
  console.log(e);
}
const coins = [
  {
    nameEn: "Contents Protocol Token",
    symbol: "CPT",
    nameKo: "콘텐츠프로토콜"
  },
  { nameEn: "Polymath", symbol: "POLY", nameKo: "폴리매쓰" },
  { nameEn: "Bitcoin", symbol: "BTC", nameKo: "비트코인" },
  { nameEn: "Ada", symbol: "ADA", nameKo: "에이다" },
  { nameEn: "Theta Fuel", symbol: "TFUEL", nameKo: "쎄타퓨엘" },
  { nameEn: "Ripple", symbol: "XRP", nameKo: "리플" },
  { nameEn: "Cosmo Coin", symbol: "COSM", nameKo: "코스모코인" },
  { nameEn: "Bitcoin Cash", symbol: "BCH", nameKo: "비트코인캐시" },
  { nameEn: "Power ledger", symbol: "POWR", nameKo: "파워렛저" },
  { nameEn: "TRON", symbol: "TRX", nameKo: "트론" },
  { nameEn: "Ethereum", symbol: "ETH", nameKo: "이더리움" },
  { nameEn: "Groestlcoin", symbol: "GRS", nameKo: "그로스톨코인" },
  { nameEn: "0x Protocol", symbol: "ZRX", nameKo: "제로엑스" },
  { nameEn: "EOS", symbol: "EOS", nameKo: "이오스" },
  { nameEn: "Enjin", symbol: "ENJ", nameKo: "엔진코인" },
  { nameEn: "Moss Coin ", symbol: "MOC", nameKo: "모스코인" },
  { nameEn: "QuarkChain ", symbol: "QKC", nameKo: "쿼크체인" },
  { nameEn: "Einsteinium ", symbol: "EMC2", nameKo: "아인스타이늄" },
  { nameEn: "BitTorrent ", symbol: "BTT", nameKo: "비트토렌트" },
  { nameEn: "SteemST", symbol: "STEEM", nameKo: "스팀" },
  { nameEn: "Icon", symbol: "ICX", nameKo: "아이콘" },
  { nameEn: "Lumen", symbol: "XLM", nameKo: "스텔라루멘" },
  { nameEn: "Storj", symbol: "STORJ", nameKo: "스토리지" },
  {
    nameEn: "Basic Attention Token ",
    symbol: "BAT",
    nameKo: "베이직어텐션토큰"
  },
  { nameEn: "OmiseGo", symbol: "OMG", nameKo: "오미세고" },
  { nameEn: "IOTA", symbol: "IOTA", nameKo: "아이오타" },
  { nameEn: "Qtum", symbol: "QTUM", nameKo: "퀀텀" },
  { nameEn: "Theta Token", symbol: "THETA", nameKo: "쎄타토큰" },
  { nameEn: "Zilliqa", symbol: "ZIL", nameKo: "질리카" },
  { nameEn: "Mainframe", symbol: "MFT", nameKo: "메인프레임" },
  { nameEn: "aelf", symbol: "ELF", nameKo: "엘프" },
  { nameEn: "Refereum", symbol: "RFR", nameKo: "리퍼리움" },
  { nameEn: "Sirin Token", symbol: "SRN", nameKo: "시린토큰" },
  { nameEn: "MediBloc", symbol: "MEDX", nameKo: "메디블록" },
  { nameEn: "Storm", symbol: "STORM", nameKo: "스톰" },
  { nameEn: "Sentinel Protocol ", symbol: "UPP", nameKo: "센티넬프로토콜" },
  { nameEn: "DMarket", symbol: "DMT", nameKo: "디마켓" },
  { nameEn: "Endor ", symbol: "EDR", nameKo: "엔도르" },
  { nameEn: "AdEx", symbol: "ADX", nameKo: "애드엑스" },
  { nameEn: "Metal ", symbol: "MTL", nameKo: "메탈" },
  { nameEn: "ONG", symbol: "ONG", nameKo: "온톨로지가스" },
  { nameEn: "Bitcoin SV", symbol: "BSV", nameKo: "비트코인에스브이" },
  { nameEn: "Gifto", symbol: "GTO", nameKo: "기프토" },
  { nameEn: "Kyber Network", symbol: "KNC", nameKo: "카이버네트워크" },
  { nameEn: "Stratis", symbol: "STRAT", nameKo: "스트라티스" },
  {
    nameEn: "Status Network Token",
    symbol: "SNT",
    nameKo: "스테이터스네트워크토큰"
  },
  { nameEn: "Siacoin", symbol: "SC", nameKo: "시아코인" },
  { nameEn: "Ethereum Classic", symbol: "ETC", nameKo: "이더리움클래식" },
  { nameEn: "Everipedi", symbol: "IQ", nameKo: "에브리피디아" },
  { nameEn: "Mercury", symbol: "MER", nameKo: "머큐리" },
  { nameEn: "NEO", symbol: "NEO", nameKo: "네오" },
  { nameEn: "IOST", symbol: "IOST", nameKo: "아이오에스티" },
  { nameEn: "Litecoin", symbol: "LTC", nameKo: "라이트코인" },
  { nameEn: "OST", symbol: "OST", nameKo: "오에스티" },
  { nameEn: "PIVX", symbol: "PIVX", nameKo: "피벡스" },
  { nameEn: "Ontology", symbol: "ONT", nameKo: "온톨로지" },
  { nameEn: "Zcash", symbol: "ZEC", nameKo: "지캐시" },
  { nameEn: "NEM", symbol: "XEM", nameKo: "넴" },
  { nameEn: "Vertcoin", symbol: "VTC", nameKo: "버트코인" },
  { nameEn: "Ark", symbol: "ARK", nameKo: "아크" },
  { nameEn: "Loom Network", symbol: "LOOM", nameKo: "룸네트워크" },
  { nameEn: "Civic", symbol: "CVC", nameKo: "시빅" },
  { nameEn: "Ardor", symbol: "ARDR", nameKo: "아더" },
  { nameEn: "adToken", symbol: "ADT", nameKo: "애드토큰" },
  { nameEn: "GAS ", symbol: "GAS", nameKo: "가스" },
  { nameEn: "SteemDollars", symbol: "SBD", nameKo: "스팀달러" },
  { nameEn: "Waves", symbol: "WAVES", nameKo: "웨이브" },
  { nameEn: "WAX ", symbol: "WAX", nameKo: "왁스" },
  { nameEn: "Golem", symbol: "GNT", nameKo: "골렘" },
  { nameEn: "Ignis ", symbol: "IGNIS", nameKo: "이그니스" },
  { nameEn: "Bitcoin Gold", symbol: "BTG", nameKo: "비트코인골드" },
  { nameEn: "Lisk", symbol: "LSK", nameKo: "리스크" },
  { nameEn: "Monero", symbol: "XMR", nameKo: "모네로" },
  { nameEn: "Augur", symbol: "REP", nameKo: "어거" },
  { nameEn: "Dash", symbol: "DASH", nameKo: "대시" },
  { nameEn: "Komodo", symbol: "KMD", nameKo: "코모도" },
  { nameEn: "Crypto.com", symbol: "MCO", nameKo: "크립토닷컴" },
  { nameEn: "Decred", symbol: "DCR", nameKo: "디크레드" },
  { nameEn: "Genesis Vision", symbol: "GVT", nameKo: "제네시스 비전" },
  { nameEn: "Kronn", symbol: "KREX", nameKo: "크론" },
  { nameEn: "Binance Coin", symbol: "BNB", nameKo: "바이낸스 코인" },
  { nameEn: "FNB Token", symbol: "FNB", nameKo: "FNB Token" },
  { nameEn: "Xtock", symbol: "XTX", nameKo: "엑스탁" },
  { nameEn: "Artista Coin", symbol: "ARTS", nameKo: "아티스타" },
  { nameEn: "Electric Vehicle Zone", symbol: "EVZ", nameKo: "이브이지" },
  { nameEn: "Dream Catcher", symbol: "DRC", nameKo: "드림캐쳐" },
  { nameEn: "Alphacon", symbol: "ALP", nameKo: "알파콘" },
  { nameEn: "Bolt", symbol: "BOLT", nameKo: "볼트" },
  { nameEn: "Game X Coin", symbol: "GXC", nameKo: "게임엑스코인" },
  { nameEn: "Cloudbric", symbol: "CLB", nameKo: "클라우드브릭" },
  { nameEn: "RealTract", symbol: "RET", nameKo: "리얼트랙트" },
  { nameEn: "UUNIO", symbol: "UUNIO", nameKo: "유니오" },
  { nameEn: "Deal Coin", symbol: "DEAL", nameKo: "딜" },
  {
    nameEn: "Contents Neutrality Network",
    symbol: "CNN",
    nameKo: "콘텐츠 뉴트럴리티 네트워크"
  },
  { nameEn: "Ravencoin", symbol: "RVN", nameKo: "레이븐코인" },
  { nameEn: "Dexter", symbol: "DXR", nameKo: "덱스터" },
  { nameEn: "Arbi Token", symbol: "ARBI", nameKo: "아비토큰" },
  { nameEn: "Zper", symbol: "ZPR", nameKo: "지퍼" },
  { nameEn: "Horizen", symbol: "ZEN", nameKo: "호라이즌" },
  { nameEn: "Holo", symbol: "HOT", nameKo: "홀로" },
  { nameEn: "Bitsonic Coin", symbol: "BSC", nameKo: "비트소닉코인" },
  { nameEn: "Verge", symbol: "XVG", nameKo: "버지" },
  { nameEn: "Dexter G", symbol: "DXG", nameKo: "덱스터지" },
  { nameEn: "YGGDRASH", symbol: "YEED", nameKo: "이그드라시" },
  { nameEn: "Decentraland", symbol: "MANA", nameKo: "디센트럴랜드" },
  { nameEn: "POA Network", symbol: "POA", nameKo: "피오에이 네트워크" },
  { nameEn: "Insureum", symbol: "ISR", nameKo: "인슈어리움" },
  { nameEn: "District 0x", symbol: "DNT", nameKo: "디스트릭트0x" },
  { nameEn: "MVL Chain", symbol: "MVL", nameKo: "엠블" },
  { nameEn: "APOT", symbol: "APOT", nameKo: "에이팟" },
  { nameEn: "Pundi X", symbol: "NPXS", nameKo: "펀디엑스" },
  { nameEn: "Viacoin", symbol: "VIA", nameKo: "비아코인" },
  { nameEn: "Wanchain", symbol: "WAN", nameKo: "완체인" },
  { nameEn: "Nucleus Vision", symbol: "NCASH", nameKo: "뉴클리어스 비전" },
  { nameEn: "ROM", symbol: "ROM", nameKo: "롬" },
  {
    nameEn: "Moeda Loyalty Points",
    symbol: "MDA",
    nameKo: "모에다 로열티 포인츠"
  },
  { nameEn: "Funfair", symbol: "FUN", nameKo: "펀페어" },
  { nameEn: "Red Pulse Phoenix", symbol: "PHX", nameKo: "레드펄스 피닉스" },
  { nameEn: "Aeron", symbol: "ARN", nameKo: "에어론" },
  { nameEn: "Etherparty", symbol: "FUEL", nameKo: "이더파티" },
  { nameEn: "Blox", symbol: "CDT", nameKo: "블럭스" },
  {
    nameEn: "Ripio Credit Network",
    symbol: "RCN",
    nameKo: "리피오 크레딧 네트워크"
  },
  { nameEn: "GoChain", symbol: "GO", nameKo: "고체인" },
  { nameEn: "ETHLend", symbol: "LEND", nameKo: "이더랜드" },
  { nameEn: "Dock", symbol: "DOCK", nameKo: "독" },
  { nameEn: "Nano", symbol: "NANO", nameKo: "나노" },
  {
    nameEn: "Paxos Standard Token",
    symbol: "PAX",
    nameKo: "팍소스 스탠다드 토큰"
  },
  { nameEn: "Waltonchain", symbol: "WTC", nameKo: "월튼체인" },
  { nameEn: "IoTeX", symbol: "IOTX", nameKo: "아이오텍스" },
  { nameEn: "Selfkey", symbol: "KEY", nameKo: "셀프키" },
  { nameEn: "VeChain", symbol: "VET", nameKo: "비체인" },
  { nameEn: "AppCoins", symbol: "APPC", nameKo: "앱코인즈" },
  { nameEn: "Aion", symbol: "AION", nameKo: "아이온" },
  { nameEn: "Cindicator", symbol: "CND", nameKo: "신디케이터" },
  { nameEn: "Neblio", symbol: "NEBL", nameKo: "네블리오" },
  { nameEn: "Chainlink", symbol: "LINK", nameKo: "체인링크" },
  { nameEn: "YOYOW", symbol: "YOYO", nameKo: "요요우" },
  { nameEn: "Skycoin", symbol: "SKY", nameKo: "스카이코인" },
  { nameEn: "HyperCash", symbol: "HC", nameKo: "하이퍼캐쉬" },
  { nameEn: "Modum", symbol: "MOD", nameKo: "모덤토큰" },
  { nameEn: "Bitcoin Diamond", symbol: "BCD", nameKo: "비트코인 다이아몬드" },
  { nameEn: "Ambrosus", symbol: "AMB", nameKo: "앰브로서스" },
  { nameEn: "Nexus", symbol: "NXS", nameKo: "넥서스" },
  { nameEn: "Qlink", symbol: "QLC", nameKo: "큐링크" },
  {
    nameEn: "Blockmason Credit Protocol",
    symbol: "BCPT",
    nameKo: "블록메이슨"
  },
  { nameEn: "Time New Bank", symbol: "TNB", nameKo: "타임뉴뱅크" },
  { nameEn: "Po.et", symbol: "POE", nameKo: "포엣" },
  { nameEn: "CyberMiles", symbol: "CMT", nameKo: "사이버마일즈" },
  { nameEn: "Viberate", symbol: "VIB", nameKo: "바이버레이트" },
  { nameEn: "Mithril", symbol: "MITH", nameKo: "미스릴" },
  { nameEn: "Ethos", symbol: "ETHOS", nameKo: "에토스" },
  { nameEn: "TenX", symbol: "PAY", nameKo: "텐엑스" },
  { nameEn: "Loopring", symbol: "LRC", nameKo: "루프링" },
  { nameEn: "Aeternity", symbol: "AE", nameKo: "애터니티" },
  { nameEn: "Populous", symbol: "PPT", nameKo: "파퓰러스" },
  { nameEn: "Cortex", symbol: "CTXC", nameKo: "코르텍스" },
  { nameEn: "IoT Chain", symbol: "ITC", nameKo: "아이오티체인" },
  { nameEn: "TrueChain", symbol: "TRUE", nameKo: "트루체인" },
  { nameEn: "Arcblock", symbol: "ABT", nameKo: "아크블록" },
  { nameEn: "OneRoot Network", symbol: "RNT", nameKo: "원루트 네트워크" },
  { nameEn: "PlayCoin", symbol: "PLY", nameKo: "플레이코인" },
  { nameEn: "Primas", symbol: "PST", nameKo: "프리마스" },
  { nameEn: "SALT", symbol: "SALT", nameKo: "솔트" },
  {
    nameEn: "Raiden Network Token",
    symbol: "RDN",
    nameKo: "레이든네트워크토큰"
  },
  { nameEn: "Insolar", symbol: "INS", nameKo: "아이앤에스" },
  { nameEn: "Bezant", symbol: "BZNT", nameKo: "베잔트" },
  { nameEn: "Odyssey", symbol: "OCN", nameKo: "오디세이" },
  {
    nameEn: "The Midas Touch Gold",
    symbol: "TMTG",
    nameKo: "더마이더스터치골드"
  },
  { nameEn: "WeShow Token", symbol: "WET", nameKo: "위쇼토큰" },
  { nameEn: "AMO Coin", symbol: "AMO", nameKo: "아모코인" },
  { nameEn: "Ether Zero", symbol: "ETZ", nameKo: "이더제로" },
  { nameEn: "APIS", symbol: "APIS", nameKo: "아피스" },
  { nameEn: "DACC", symbol: "DACC", nameKo: "디에이씨씨" },
  { nameEn: "Davinci Coin", symbol: "DAC", nameKo: "다빈치" },
  { nameEn: "BHPCash", symbol: "BHP", nameKo: "비에이치피" },
  { nameEn: "Hyundai DAC", symbol: "HDAC", nameKo: "에이치닥" },
  { nameEn: "Cube", symbol: "AUTO", nameKo: "큐브" },
  { nameEn: "Dex", symbol: "DEX", nameKo: "덱스" },
  { nameEn: "O2O Pay", symbol: "O2O", nameKo: "오투오페이" },
  { nameEn: "Femi Coin", symbol: "FEMI", nameKo: "페미코인" },
  { nameEn: "Internation University Coin", symbol: "IUC", nameKo: "유니코인" },
  { nameEn: "Sun Chain", symbol: "SUNC", nameKo: "썬체인" },
  { nameEn: "TudaToken", symbol: "TUDA", nameKo: "튜다" },
  { nameEn: "Frontier", symbol: "FRNT", nameKo: "프론티어" },
  { nameEn: "Lisk", symbol: "LISK", nameKo: "리스크" },
  { nameEn: "Kin", symbol: "KIN", nameKo: "킨" },
  { nameEn: "Maximine Coin", symbol: "MXM", nameKo: "맥시마인 코인" },
  { nameEn: "Revain", symbol: "R", nameKo: "리베인" },
  { nameEn: "ROMTV", symbol: "ROMTV", nameKo: "롬티비" },
  { nameEn: "Nxt", symbol: "NXT", nameKo: "엔엑스티" },
  { nameEn: "Nexo", symbol: "NEXO", nameKo: "넥소" },
  { nameEn: "Next", symbol: "NET", nameKo: "넥스트" },
  { nameEn: "Blockmason Link", symbol: "BLINK", nameKo: "블록메이슨링크" }
];

exports = module.exports = functions.https.onRequest(async (req, res) => {
  await coins.reduce(async (promise, coin) => {
    await promise;
    await admin
      .firestore()
      .collection("coins")
      .add({
        nameEn: coin.nameEn,
        nameKo: coin.nameKo,
        symbol: coin.symbol
      })
      .then(() => {})
      .catch(err => {
        console.log(err);
      });
  }, Promise.resolve());
  await console.log("Set coin done");
  await res.send("Done");
});
