export const SELECT_COIN = "SELECT_COIN",
  SELECT_COIN_ERROR = "SELECT_COIN_ERROR",
  SELECT_EXCHANGE = "SELECT_EXCHANGE",
  SELECT_EXCHANGE_ERROR = "SELECT_EXCHANGE_ERROR",
  RECEIVE_CANDLE_DATA = "RECEIVE_CANDLE_DATA",
  RECEIVE_ORDERBOOK_DATA = "RECEIVE_ORDERBOOK_DATA",
  RECEIVE_TRADES_DATA = "RECEIVE_TRADES_DATA",
  SEARCH_COIN = "SEARCH_COIN";
